### ISSUE TITLE
Taproot addresses

### ISSUE THREAD

**Issue by SergeevDmitry** [keng42/xwallet#3]
Hi,

Do you plan to add [taproot](https://github.com/bitcoin/bips/blob/master/bip-0086.mediawiki) addresses?

I wanted to provide a PR, but it requires [btcd](github.com/btcsuite/btcd) package upgrade and your github.com/keng42/bchutil package depends on btcd package and should be upgraded too. It seems that bchutil package is not on the github, so, I can't provide a PR there.

**Comment by keng42** [comment]
Hi, [keng42/bchutil](https://github.com/keng42/bchutil) is a fork of [cpacia/bchutil](https://github.com/cpacia/bchutil), it looks outdated and I was going to rewrite it. But I don't have the time or motivation to do it.
Welcome and thank you for the PR!

**Comment by SergeevDmitry** [comment]
Hi, thanks for pointing me out. I created a [PR](https://github.com/keng42/bchutil/pull/1) to the keng42/bchutil with btcd package upgrade. Once you accept it, I'll create a separate PR to xwallet with btcd package upgrade too, because I need it in my project. And after that I'll create another PR with taproot

**Comment by keng42** [comment]
Well done 👍

**Comment by SergeevDmitry** [comment]
Hi @keng42, could you accept another PR in the bchutil project, please?

**Comment by keng42** [comment]
Sorry, I didn't receive a notification.  It's done now.

**Comment by SergeevDmitry** [comment]
Thank you
