### ISSUE TITLE
Passphrase Support?

### ISSUE THREAD

**Issue by adamsih300u** [keng42/xwallet#5]
Hello,

This tool looks amazing. I am looking to do some automated lookups, but need to be able to support the passphrase function. Is there any option for that currently, or is it planned?

Thanks,
Adam

**Comment by keng42** [comment]
Hi Adam,

Since this project is more for generating wallets than for ongoing wallet management now, there is no need to add a passphrase.  But it may be needed when completing transaction-related functions in the future.
